Changing prefixes, adding a general function and short vignette on release branches
PIP-Technical-Team/pipaux pull request #108
Opened 2024-12-23 18:00 UTC by RossanaTat

2025-01-13 18:29 UTC, randrescastaneda requested changes

2025-01-13 18:29 UTC, randrescastaneda commented on R/utils.R
> +                              package_name = "pipaux",
Hi @RossanaTat , 

Is this necessary? I don't think we will use this function in a different package.

2025-01-13 18:29 UTC, randrescastaneda commented on R/utils.R
> +call_aux_function <- function(measure,
Hello @RossanaTat , 

Could you provide some examples of how to use this function? Also, I’m not entirely sure I like the name, unless this is meant to be an intermediate function that will be used elsewhere.

What I had envisioned is a function that can either update or load any auxiliary file. Could you explain how this works so I can better understand what you have in mind?

Thank you!

2025-01-14 22:27 UTC, RossanaTat commented on R/utils.R
> +call_aux_function <- function(measure,
Hi @randrescastaneda, thanks for your feedback, I get your point. Two things here:
**(1.)** The `call_aux_function()` I developed is intended to simplify working with auxiliary data files by allowing to call a single, general function for any measure or action. This for example reduces redundancy when working with different measures and actions. However, it still relies on the existing aux_* functions in the backend, so it doesn't fundamentally change how the loading or updating of files is currently implemented. For example,

`call_aux_function(measure = "sna", branch = "DEV", action = "load")` gives the same result as `aux_sna(branch = "DEV", action = "load")`. 
Or, `call_aux_function(measure = "wdi", branch = "DEV", action = "update")` achieves the same as `aux_wdi(branch = "DEV", action = "update")`

I am assuming what you're envisioning is a more independent solution—one that doesn't rely on the existing aux_* functions and somehow improves how the entire process is handled? 

**(2.)** Regarding naming, better alternatives are: `handle_aux_data()`, `update_or_load_aux()`, or `use_aux_function()`.

On **next steps**, maybe we need a new function designed to efficiently update or load auxiliary data files while still accommodating specific requirements (e.g., updates via GitHub, World Bank API for WDI, or hardcoded cases like in PPPs). I've actually encountered some issues with the current aux_* functions, so the new function could address those as well (might need to double check with you on those issues). 

Could we talk about it, so I can better understand the direction we're aiming for?

For now, I propose keeping this PR focused on prefixes and the branch release management vignette, then opening a new branch to tackle the new function. Does this work for you?

Thank you. Best,

2025-01-14 22:28 UTC, RossanaTat commented on R/utils.R
> +                              package_name = "pipaux",
Got it, removed `package_name` argument!

2025-01-14 23:38 UTC, randrescastaneda commented on R/utils.R
> +call_aux_function <- function(measure,
Hi @RossanaTat, 

Thank you so much.let's talk about it tomorrow morning.Best.

2025-01-14 23:41 UTC, randrescastaneda requested changes
Hi @Rossanatat, 
Thanks. Please make sure that this RR does not have any conflict with Tefera's changes. Thank you so much.

2025-01-15 01:03 UTC, RossanaTat commented
[like]  ROSSANA TATULLI reacted to your message:
________________________________
From: R.Andrés Castañeda ***@***.***>
Sent: Tuesday, January 14, 2025 11:41:22 PM
To: PIP-Technical-Team/pipaux ***@***.***>
Cc: ROSSANA TATULLI ***@***.***>; Mention ***@***.***>
Subject: Re: [PIP-Technical-Team/pipaux] Changing prefixes, adding a general function and short vignette on release branches (PR #108)


@randrescastaneda requested changes on this pull request.

Hi @RossanaTat<https://github.com/RossanaTat>,
Thanks. Please make sure that this RR does not have any conflict with Tefera's changes. Thank you so much.

—
Reply to this email directly, view it on GitHub<https://github.com/PIP-Technical-Team/pipaux/pull/108#pullrequestreview-2551255248>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BD5CFDLJGCK3P67VDUDIL2L2KWOCFAVCNFSM6AAAAABUDOJZO6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNJRGI2TKMRUHA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-15 01:03 UTC, RossanaTat commented
[like]  ROSSANA TATULLI reacted to your message:
________________________________
From: R.Andrés Castañeda ***@***.***>
Sent: Tuesday, January 14, 2025 11:38:20 PM
To: PIP-Technical-Team/pipaux ***@***.***>
Cc: ROSSANA TATULLI ***@***.***>; Mention ***@***.***>
Subject: Re: [PIP-Technical-Team/pipaux] Changing prefixes, adding a general function and short vignette on release branches (PR #108)


@randrescastaneda commented on this pull request.

________________________________

In R/utils.R<https://github.com/PIP-Technical-Team/pipaux/pull/108#discussion_r1915752929>:

> \ No newline at end of file
+}
+
+#' Call auxiliary function for a specified measure
+#'
+#' @param measure character: Name of the auxiliary data measure (e.g., "ppp")
+#' @param package_name character: Name of the package containing the auxiliary function (default is "pipaux")
+#' @param ... additional arguments to pass to the auxiliary function
+#'
+#' @return The result of the auxiliary function call.
+call_aux_function <- function(measure,


Hi @RossanaTat<https://github.com/RossanaTat>,

Thank you so much.let's talk about it tomorrow morning.Best.

—
Reply to this email directly, view it on GitHub<https://github.com/PIP-Technical-Team/pipaux/pull/108#discussion_r1915752929>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BD5CFDNFCLZI32WVHGU5JX32KWNWZAVCNFSM6AAAAABUDOJZO6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNJRGI2TENJQGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-16 16:43 UTC, RossanaTat commented
Hi @randrescastaneda, I believe this PR is ready for merging. I removed the general function, so that this PR is only about prefixes and vignette on release branches. I will work on a different branch to develop the general `aux` function and dependency workflow. Thank you!

2025-01-17 22:18 UTC, randrescastaneda reviewed
all good, just make the change that we discussed. Thanks.

2025-01-22 14:55 UTC, RossanaTat commented
> all good, just make the change that we discussed. Thanks.

Hi @randrescastaneda, thank you, I have reorganized all functions across files and pushed.

2025-01-22 16:56 UTC, randrescastaneda approved these changes

2025-01-22 16:56 UTC, merged