Auto aux update check
PIP-Technical-Team/pipaux pull request #94
Opened 2024-02-01 03:08 UTC by shahronak47

Clickup task - https://app.clickup.com/t/868763th2 

I think I have a fix, but let's test it when we have aux data to update before merging.

2024-02-02 15:12 UTC, randrescastaneda requested changes
Hi @shahronak47 , 

I noticed you're relying on the modified date to track changes in aux files. While that works, it could be risky if they're edited multiple times in a day.

For enhanced security and clarity, I propose using the hashes created by the `pipfun::pip_sign_save()` function. This function calculates and saves a unique hash each time an aux file is updated, ensuring precise identification of different versions.

Please review the details of `pipfun::pip_sign_save()` and the hash files saved. Let me know if you agree with a hash-based approach. If not, we can explore further improvements to the current date-based method.

Thanks.

2024-02-02 15:12 UTC, randrescastaneda commented on R/auto_aux_update.R
> +        dplyr::filter(as.Date(time_last_update) == Sys.Date())
I don't Think this will work well, especially since it is possible to update the same file several times a day

2024-02-03 03:05 UTC, shahronak47 commented
> Hi @shahronak47 ,
> 
> I noticed you're relying on the modified date to track changes in aux files. While that works, it could be risky if they're edited multiple times in a day.
> 
> For enhanced security and clarity, I propose using the hashes created by the `pipfun::pip_sign_save()` function. This function calculates and saves a unique hash each time an aux file is updated, ensuring precise identification of different versions.
> 
> Please review the details of `pipfun::pip_sign_save()` and the hash files saved. Let me know if you agree with a hash-based approach. If not, we can explore further improvements to the current date-based method.
> 
> Thanks.

Instead of today's date we can look if the file is updated in last x mins. We can define x as 5 or 10 mins. Using hash is more safer  however, it can be a lot of work to get that hash for each file which is updated because `pip_sign_save` is not explicitly called in our function.

2024-02-05 15:45 UTC, randrescastaneda commented
> > Hi @shahronak47 ,
> > I noticed you're relying on the modified date to track changes in aux files. While that works, it could be risky if they're edited multiple times in a day.
> > For enhanced security and clarity, I propose using the hashes created by the `pipfun::pip_sign_save()` function. This function calculates and saves a unique hash each time an aux file is updated, ensuring precise identification of different versions.
> > Please review the details of `pipfun::pip_sign_save()` and the hash files saved. Let me know if you agree with a hash-based approach. If not, we can explore further improvements to the current date-based method.
> > Thanks.
> 
> Instead of today's date we can look if the file is updated in last x mins. We can define x as 5 or 10 mins. Using hash is more safer however, it can be a lot of work to get that hash for each file which is updated because `pip_sign_save` is not explicitly called in our function.

Hi @shahronak47 , 

Right where the aux file is saved, there is another file called `yyy_datasignature`, where `yyy` stands for the name of the auxiliary file (e.g., cpi, gdp, ppp, etc). That file contains the hash. Just read it before the `*update()` process starts. Does it make sense? Please, let me know. Best

2024-03-04 15:28 UTC, merged